### ISSUE TITLE
我无法启动我的机器人

### ISSUE THREAD

**Issue by 2b-creator** [zmx0142857/qq-tex-bot#1]
![image](https://user-images.githubusercontent.com/81023606/185528943-0783670b-476e-4b83-8042-0c41be090ef9.png)
我尝试了很久很久很久，快自闭了，谢谢大佬帮助！

**Comment by zmx0142857** [comment]
这个错误意思是没有连接上 miral-api-http 插件提供的服务。mcl 启动过程中是否有报错呢。mirai 各插件的版本是一个大坑，可以参考 [README.md](https://github.com/zmx0142857/qq-tex-bot#trouble-shooting) 中 mirai 的 config 文件

**Comment by 2b-creator** [comment]
> 这个错误意思是没有连接上 miral-api-http 插件提供的服务。mcl 启动过程中是否有报错呢。mirai 各插件的版本是一个大坑，可以参考 [README.md](https://github.com/zmx0142857/qq-tex-bot#trouble-shooting) 中 mirai 的 config 文件

那我现在试试
哎，其实我之前在gitee上发过issue😂，然后如今还是没有回复，然后就没搞
然后现在突然又找到了GitHub这边
![image](https://user-images.githubusercontent.com/81023606/185530347-dadfee35-2d8c-4cc2-9af6-791e7f8a5395.png)

**Comment by zmx0142857** [comment]
> 哎，其实我之前在gitee上发过issue😂，然后如今还是没有回复，然后就没搞

gitee 那边不打算更新了

**Comment by 2b-creator** [comment]
十分感谢！
